### ISSUE TITLE
Filter based on completion time has errors, around line 1999

### ISSUE THREAD

**Issue by rcalinjageman** [seanrife/TM-RRR#1]
Around line 199 of Analysis.R the current lab's data is filtered to exclude participants who took less than 300s to complete the study.  

```
# Exclude if participant took less than 5 minutes to complete the survey
df <- df[df$interviewtime < 300]

```
There are a couple of problems.  

- interviewtime has not been define yet
- there is a missing comma to specify all columns should be returned
- this seems to keep only those who took less than 300s, but I think the intention was to keep those who took more than that time

I suggest:
```
  # Exclude if participant took less than 5 minutes to complete the survey
  df$interviewtime <- as.numeric(as.POSIXct(df$submitdate, format = "%Y-%m-%d %H:%M:%S")) - as.numeric(as.POSIXct(df$startdate, format = "%Y-%m-%d %H:%M:%S"))
  df <- df[df$interviewtime > 300, ]
```

**Comment by seanrife** [comment]
This was actually due to the way we were dropping columns, which is now more robust (see https://github.com/seanrife/TM-RRR/commit/75dadb6e3f96a8ae009e2a9b3cb1b8fe3fa97e30 and https://github.com/seanrife/TM-RRR/commit/fc0e4e5cb51d706e204ecabf38ce442bc47a8218).

`interviewtime` is the survey system's time record, which should be very accurate, and is now present. Also fixed the bugs re: the cutoff.

 https://github.com/seanrife/TM-RRR/commit/142dc34be8182fe195d73ea9ad2bcee1ed0deab3
